fortune: true

# Only blocks broken in regions that start with this
# will be submitted to the players backpack.
region-name-id: 'mine'

number-format: '#,###.##'

autosell:

  # Distance between sells in ticks.
  period: 1200

  notification:

    message:
      enabled: true
      message:
        - '<RAINBOW1>summary: ${amount}</RAINBOW>'

    sound:
      enabled: true
      sound: 'BLOCK_GRAVEL_STEP'

booster:

  # The notification sent when a players booster expires.
  expire-notification:

    message:
      enabled: true
      message:
        - '<#FF0000>&lYour {multi} booster for {duration} {time_unit} has expired!'
    sound:
      enabled: true
      sound: 'BLOCK_GRAVEL_STEP'